[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildCommand = "cd backend"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 