[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 